apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-from-folders
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/tonyrizzotto/charts.git
        revision: main
        directories:
          - path: apps/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/tonyrizzotto/charts.git
        targetRevision: main
        path: 'apps/{{path.basename}}'
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: main # this is the name of the namespace created in apps/edge/namespace.yaml
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
